### ISSUE TITLE
运行  cherub start报错

### ISSUE THREAD

**Issue by Peterppan** [l-zhi/marrycard#2]
Error: Cannot find module 'G:\婚礼\marrycard\index-start'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by l-zhi** [comment]
> Error: Cannot find module 'G:\婚礼\marrycard\index-start'
> at Function.Module._resolveFilename (module.js:470:15)
> at Function.Module._load (module.js:418:25)
> at Module.runMain (module.js:605:10)
> at run (bootstrap_node.js:420:7)
> at startup (bootstrap_node.js:139:9)
> at bootstrap_node.js:535:3

npm install after download the project
